### ISSUE TITLE
Can you please solve this error?

### ISSUE THREAD

**Issue by SethuBargavi** [jhayes14/GAN#5]
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/Python Projects/myFirstPython/train.py", line 196, in <module>
    train(path = args.path, batch_size = args.batch_size, EPOCHS = args.epochs)
  File "C:/Users/admin/Desktop/Python Projects/myFirstPython/train.py", line 111, in train
    d_loss = discriminator.train_on_batch(Xd, yd)
  File "C:\Users\admin\AppData\Roaming\Python\Python35\site-packages\keras\models.py", line 1069, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\admin\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 1843, in train_on_batch
    check_batch_axis=True)
  File "C:\Users\admin\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 1430, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\admin\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 70, in _standardize_input_data
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
  File "C:\Users\admin\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 70, in <listcomp>
    data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
AttributeError: 'int' object has no attribute 'ndim'

**Comment by innarid** [comment]
I've got the same
